#!/bin/bash

if [[ $# != 1 ]]; then 
	echo "Usage: $0 [guestname]"
	exit 1
fi

if ! virsh list --all | grep -q $1; then 
	echo "guest $1 doesn't seem to exist"
	exit 1
fi

if ! virsh dumpxml $1 | grep -A 3 "<serial type='file'>" | grep "source path=" | awk -F"'" '{print $2}'; then
	exit 1
else
	exit 0
fi
